baseURL: "https://www.straalatelier.com/"
title: Straal Atelier Val-Meer
relativeURLs: false
disableKinds:
  - section
  - taxonomy
  - taxonomyTerm
  - RSS
disableHugoGeneratorInject: true
enableGitInfo: true
enableRobotsTXT: true
defaultContentLanguage: nl
defaultContentLanguageInSubdir: true
timeout: 60000
