nl:
  weight: 1
  languageName: Nederlands
  title: Straal Atelier Val-Meer
  description: Voor het Luchtgommen van alle soorten en types hout, het Fijnstralen van Carrosserie en Glasparelstralen van Inox en Aluminium.
  meta:
    keywords: zandstralen, luchtgommen, parelstralen, reinigen, glasparel, bicarbonaat, spuiten, roest verwijderen, polijsten, aerogommage
fr:
  weight: 2
  languageName: Français
  title: Straal Atelier Val-Meer
  description: Pour les gommes à air de tous types et types de bois, de faisceaux fins de carrosserie et de faisceaux de panneau de verre d'acier inoxydable et d'aluminium.
  meta:
    keywords: sablage, sablage à la soude, gommage à l'air, grenaillage, perle de verre, bicarbonate de soude, pulvérisation, élimination de la rouille, polissage, aérogommage
