slogan: Voor het Luchtgommen van alle soorten en types hout, het Fijnstralen van Carrosserie en Glasparelstralen van Inox en Aluminium.
email: info@straalatelier.com
phone: "+32478766843"
adrStreet: Vijfkruisenstraat 11a
adrPostcode: B-3770
adrLocality: RIEMST
adrCountry: BELGIË