slogan: Voor het Luchtgommen van alle soorten en types hout, het Fijnstralen van Carrosserie en Glasparelstralen van Inox en Aluminium.
email: info@straalatelier.com
phone: "+32478766843"
adrStreet: Vijfkruisenstraat 11a
adrPostcode: B-3770
adrCity: Val-Meer
adrLocality: RIEMST
adrCountry: BELGIË
keywords:
  - glasparelstralen
  - meubels
  - nabehandeling
  - metaal
  - zandstralen
  - luchtgommen
images:
  - /images/showcase/IMG_20201108_170139.jpg
  - /images/showcase/kabien1.jpg
  - /images/showcase/Parelstralen.jpg
