disqus:
  disable: true
googleAnalytics:
  disable: true
instagram:
  disable: false
  simple: true
twitter:
  disable: false
  enableDNT: true
  simple: true
youtube:
  disable: false
  privacyEnhanced: true