baseURL = "https://www.straalatelier.com"
relativeURLs = false

# This is a "one page"-website, so we do not need these kinds of pages...
disableKinds = ["section", "taxonomy", "term"]
disableHugoGeneratorInject = true
enableGitInfo = true
enableRobotsTXT = true

defaultContentLanguage = "nl"
defaultContentLanguageInSubdir = true

[languages]
  [languages.nl]
    weight = 1
    languageName = "Nederlands"

    # The "title" of your website
    title = "Straal Atelier Valmeer"

    [languages.nl.params]
      # The "description" of your website. This is used in the meta data of your generated html.
      description = "Professioneel stralen van meubels, onderdelen en meer. Met zand, glasparels, bicarbonaat en meer."

      # A "copyright"-line to be added at the bottom of the page.
      # Hint: Markdown is supported in here as well. So you may e.g. add a link to your legal imprint-page.
      # copyright = "© Straal Atelier Valmeer"

      # Another "title" :-). This one is used as the site_name on the Hugo's internal
      # opengraph structured data template.
      # See https://ogp.me/ and https://gohugo.io/templates/internal#open-graph.
      title = "Straal Atelier Valmeer - Professioneel stralen van meubels, onderdelen en meer. Met zand, glasparels, bicarbonaat en meer."

      [languages.nl.params.meta]
        keywords = "zandstralen, sodastralen, luchtgommen, parelstralen, glasparel, bicarbonaat, spuiten, roest verwijderen, polijsten, aerogommage"

  [languages.fr]
    weight = 2
    languageName = "Français"

    # The "title" of your website
    title = "Straal Atelier Valmeer"

    [languages.fr.params]
      title = "Straal Atelier Valmeer - Professioneel stralen van meubels, onderdelen en meer. Met zand, glasparels, bicarbonaat en meer."
      description = "Professioneel stralen van meubels, onderdelen en meer. Met zand, glasparels, bicarbonaat en meer."

    [languages.fr.params.meta]
      keywords = "zandstralen, sodastralen, luchtgommen, parelstralen, glasparel, bicarbonaat, spuiten, roest verwijderen, polijsten, aerogommage"

[params]
    # These "images" are used for the structured data templates. This will show up, when
    # services like Twitter or Slack want to generate a preview of a link to your site.
    # See https://gohugo.io/templates/internal#twitter-cards and
    # https://gohugo.io/templates/internal#open-graph.
    images = ["images/cover-image.jpg"]

    # This theme will, by default, inject a design-by-line at the bottom of the page.
    # You can turn it off, but we would really appreciate if you don’t :-)
    # hidedesignbyline = true

[markup]
  [markup.highlight]
    noClasses = true

[module]
  [[module.mounts]]
    source = "node_modules/jquery/dist"
    target = "assets/jquery"
  [[module.mounts]]
    source = "node_modules/flickity/dist"
    target = "assets/flickity"
  [[module.mounts]]
    source = "node_modules/feather-icons/dist"
    target = "assets/feather-icons"
  [[module.mounts]]
    source = "assets"
    target = "assets"

# Privacy settings: full compliance with GDPR.
[privacy]
  [privacy.disqus]
    disable = true
  [privacy.googleAnalytics]
    disable = true
  [privacy.instagram]
    disable = false
    simple = true
  [privacy.twitter]
    disable = false
    enableDNT = true
    simple = true
  [privacy.youtube]
    disable = false
    privacyEnhanced = true
