[build]
command = "yarn run build"
publish = "public"

[build.environment]
HUGO_VERSION = "0.82.0"
HUGO_ENV = "production"

[context.deploy-preview]
command = "yarn run build --buildFuture -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
command = "yarn run build -b $DEPLOY_PRIME_URL"

[[redirects]]
  from = "/"
  to = "/fr/"
  status = 302
  force = true
  conditions = {Language = ["fr"]}

[[redirects]]
  from = "/"
  to = "/nl/"
  status = 302
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
    Referrer-Policy = "no-referrer-when-downgrade"
    Strict-Transport-Security = "max-age=63072000; includeSubdomains; preload"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "1; mode=block"
    Content-Security-Policy-Report-Only = "default-src https://www.google.com/maps/embed; child-src https://www.google.com; font-src 'self'; img-src 'self'; script-src 'self'; style-src 'self'; report-uri https://spacebabies.report-uri.com/r/d/csp/reportOnly"
    Report-To = "{\"group\":\"default\",\"max_age\":31536000,\"endpoints\":[{\"url\":\"https://spacebabies.report-uri.com/a/d/g\"}],\"include_subdomains\":true}"

[[headers]]
  for = "/site.webmanifest"
  [headers.values]
    Content-Type = "application/manifest+json; charset=UTF-8"
    Cache-Control = "public,max-age=14400"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public,max-age=31536000"

[[plugins]]
package = "netlify-plugin-is-website-vulnerable"

[[plugins]]
package = "netlify-plugin-checklinks"

[[plugins]]
package = "netlify-plugin-submit-sitemap"
