[build]
publish = "public"

[context.production]
command = "hugo --minify"

[context.production.environment]
HUGO_VERSION = "0.80.0"

[context.deploy-preview]
command = "hugo --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
command = "hugo --minify -b $DEPLOY_PRIME_URL"

[[redirects]]
from = "/"
to = "/fr/"
status = 302
force = true
conditions = {Language = ["fr"]}

[[redirects]]
from = "/"
to = "/nl/"
status = 302
force = true
