[build]
publish = "public"

[context.production]
command = "yarn run build"

[context.production.environment]
HUGO_VERSION = "0.80.0"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.deploy-preview]
command = "yarn run build --buildFuture -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
command = "yarn run build -b $DEPLOY_PRIME_URL"

[[redirects]]
from = "/"
to = "/fr/"
status = 302
force = true
conditions = {Language = ["fr"]}

[[redirects]]
from = "/"
to = "/nl/"
status = 302
force = true

[[plugins]]
package = "netlify-plugin-is-website-vulnerable"

[[plugins]]
package = "netlify-plugin-checklinks"

[[plugins]]
package = "netlify-plugin-submit-sitemap"