headers:
- for: /nl/
  values:
    X-Content-Type-Options: nosniff
    X-Frame-Options: SAMEORIGIN
    Content-Security-Policy-Report-Only: "default-src 'self' www.google.com fonts.googleapis.com; font-src 'self' fonts.gstatic.com; img-src 'self'; script-src 'self' 'unsafe-eval' 'unsafe-inline'; report-uri https://spacebabies.report-uri.com/r/d/csp/wizard"
    Report-To: "{\"group\":\"default\",\"max_age\":31536000,\"endpoints\":[{\"url\":\"https://spacebabies.report-uri.com/a/d/g\"}],\"include_subdomains\":true}"
    Permissions-Policy: geolocation=(self "https://www.google.com"), microphone=()
